services:
  app:
    container_name: "fastapi_test"
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./infrastructure/migrations/versions:/app/infrastructure/migrations/versions
      - ./api:/app/api
      - ./application:/app/application
      - ./infrastructure/db:/app/infrastructure/db
      - ./domain:/app/domain
    networks:
     - backend
  db:
    container_name: "postgres_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
     - backend

networks:
 backend:
   driver: bridge

volumes:
 db:
   driver: local